### ISSUE TITLE
Add possibility to assign a function to a declarative function

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#186]
I love declarative function but sometimes it is not convenient to write long function inside a declaration. What I would like to be able to do is the following (assuming that the function has the correct signature) : 
```python
def complex_function(self, arg1, arg2):
    # Do a lot of stuff here

enamldef MyObject(MyBaseClass):

    decl_func <= complex_function
```

If you can give me some pointers I will be happy to make a PR.

**Comment by sccolbert** [comment]
Currently, a declarative function becomes a method on the generated class. The syntax you show here is assigning a function to an instance attribute. The behavior you are requesting is more inline with how Javascript behaves instead of Python. 

Instead of new syntax, can you do what you want by defining a simple declarative function as normal, which just calls out to your larger module-level function?

**Comment by MatthieuDartiailh** [comment]
I can use a simple declarative function calling my function, my idea was just to have a kind of syntatic sugar doing the same, as it seems to me that when parsing the function could be added to the class dictionary and behave as a normal method.

But I can live without it.
