### ISSUE TITLE
Make destroyed a declarative member

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#197]
Destroyed is the only lifetime event of a declarative object that is not accessible from the declarative syntax. For consistency it would make sense to fix that (furthermore I have use cases for that, I can detail them if you want).

**Comment by sccolbert** [comment]
The declarative data for an object is removed before the `destroyed` event is triggered. So it's not possible to execute a declarative binding at that point.

**Comment by sccolbert** [comment]
If you just need a hook, to cleanup part of your tree, you can subclass the widget, reimplement `destroy`, and emit your own event before calling `super`.

**Comment by MatthieuDartiailh** [comment]
I believe you but I was under the impression that by redeclaring destroyed as declarative everything worked, I will have to look into it in more details thanks for your quick answer.

**Comment by sccolbert** [comment]
Hmm. I haven't tested, but the event listener will still be hooked up at that point, so it may actually fire. The issue is that all of the internal declarative data will be removed before that happens, so you'll likely run into a bunch of weird issues in the declarative code where data appears to be wrong:
https://github.com/nucleic/enaml/blob/master/enaml/core/declarative.py#L127

The actually listener will be detached at the super call right after `destroyed` is emitted:
https://github.com/nucleic/enaml/blob/master/enaml/core/object.py#L112

**Comment by MatthieuDartiailh** [comment]
Thanks for the details I will go with my own event then. I just hoped to avoid using standard subclassing and be able to only use the declarative syntax.
