### ISSUE TITLE
Is it possible to observe non atom objects?

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#219]
Can enaml be used with different "observable" objects that are not Atom instances?  For instance [traitlets](https://github.com/ipython/traitlets) objects,  [kivy properties](https://kivy.org/docs/api-kivy.properties.html#observe-property-changes), or any object that can be binded to a callback etc...

If so, is there a way to add/hook these into the parser?  

Thanks!

**Comment by sccolbert** [comment]
Unfortunately no. I was thinking of doing that in a new/updated version, but it's unlikely to come to fruition given my current focus.

**Comment by MatthieuDartiailh** [comment]
Is it not just a matter of using a different set of operators just like traits-enaml is doing ?

**Comment by sccolbert** [comment]
^ What this guy said. I've been out of it too long...

**Comment by frmdstryr** [comment]
Thanks for the prompt replies, will see how it's done there.

**Comment by MatthieuDartiailh** [comment]
No problem @sccolbert :)

I am working on python 3.6 compatibility and expect to be done soon. Any hope you could review my pending PRs after phosphor 1.0 ? Otherwise I think I will have to tag at least a 0.10.0 on my fork because I really need those updates for my own project and just relying on latest commit is not really good enough. Do you mind me doing so ?

**Comment by tstordyallison** [comment]
I was going to say, I've definitely written custom operators in the past...

**Comment by sccolbert** [comment]
I'll just go crawl back under my rock now :)
