### ISSUE TITLE
Add CI support for Windows

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#272]
I am believer that you aren't really supporting a platform unless you are testing on it before each release. While Enaml is developed on Windows, the CI testing is Linux only. I would like to see CI-style testing on Windows too (and MacOs, iOS and Android, but I can't help with those.)

I am happy to make a PR to add an Appveyor script, but I can't do it all - hence this issue to see if there is interest.

It will require some admin support - e.g. create a free Appveyor account and to link it to GitHub so it is run on each commit.

It may also reveal defects. I have been working on an Appveyor script for Enaml. My appveyor script is currently testing 9 configurations, but only 5 pass. Neither Pyside 1 nor Pyside 2 configurations are passing the tests. Strangely, on the Python 3.4 configurations, pytest-qt can't find PyQT4 (V1 and V2). Not sure why that is.

I do not have coverage testing working in AppVeyor, and I haven't bothered to tyd configurations with iPython/qt-console, QScintilla or matplotlib, mainly because I don't know how they relate to the code.

**Comment by MatthieuDartiailh** [comment]
Honestly I did not add windows testing mostly because there is nearly no windows specific code, but it can be interesting to have. @sccolbert will have to deal setting Appveyor, since I do not have enough privileges to do so.
As far as the configurations are concerned, Pyside was never officially supported so we can safely ignore it. Pyside 2 would be interesting to have but last time I checked some part of the Qt API was not supported. I remember seeing something similar for pytest-qt but if it is just one configuration we can ignore it.
The other configuration related to specific widgets are not platform specific so we can ignore them at least at first.

**Comment by MatthieuDartiailh** [comment]
Turns out I could add enaml to my own Appveyor account, which I did. 
You can open your PR @Julian-O

**Comment by MatthieuDartiailh** [comment]
I finally created an nucleic organization appveyor account and while the tests were passing on my account now the 3.5 build appears to be broken. The error seems quite silly. @Julian-O could you try to look into it ?

**Comment by Julian-O** [comment]
So far I have found:
* PyQT5 have released a new version within the last 24 hours.
* pytest-qt doesn't seem to recognise the new version.

So, not directly related to the Appveyor script, or Enaml at all.

I have raised [an issue against pytest-qt](https://github.com/pytest-dev/pytest-qt/issues/218), but it still leaves the question of what the best workaround approach is,

**Comment by Julian-O** [comment]
Moved to a new Issue, because this problem turned out to be unrelated to the original task.
