### ISSUE TITLE
setup.py entry point does not work with enaml.imports()

### ISSUE THREAD

**Issue by kiwi0fruit** [nucleic/enaml#321]
Entry point executables created via setup.py do not works with `with enaml.imports()`. Some error occurs (I forgot what error it was).

At the moment there exist a workaround. See example: [Enaml video app](https://github.com/kiwi0fruit/enaml-video-app) (the main idea is in [bash](https://github.com/kiwi0fruit/enaml-video-app/blob/master/enaml-video-app/scripts/enaml-video-app), [batch](https://github.com/kiwi0fruit/enaml-video-app/blob/master/enaml-video-app/scripts/enaml-video-app.bat) and [\_\_main\_\_](https://github.com/kiwi0fruit/enaml-video-app/blob/master/enaml-video-app/enaml_video_app/__main__.py) scripts). Plus adding:

```py
import inspect
import enaml_video_app
os.chdir(os.path.dirname(inspect.getfile(enaml_video_app)))
with enaml.imports():
    from enaml_video_view import Main
```

**Comment by MatthieuDartiailh** [comment]
I am a bit surprised by you issue, since I have been using setuptools entry points for a long time in this project https://github.com/Exopy/exopy (https://github.com/Exopy/exopy/blob/master/exopy/__main__.py)
Looking at you implementation, I have the following question/remarks:
- why do you write the scripts yourself rather than letting setuptools handle that for you (see https://github.com/Exopy/exopy/blob/master/setup.py) ?
- do you have a reason to use imports that do not include the full library name ? This looks like a good way to get issue with the path to me. You install a lib and try to import a module from a package without specifying the package.

**Comment by MatthieuDartiailh** [comment]
Could you clarify one thing  ? Where do you add the snippet you posted in your first post ? 
My point about import is that it would look better to me to do 
```python
with enaml.imports():
    from enaml_video_app.enaml_video_view import Main
```
and use either absolute or relative import in you library but avoid doing doing:
```python
import enaml_video_model
```
and expect you will get the right thing.

**Comment by MatthieuDartiailh** [comment]
You can have a look at how exopy is implemented.

**Comment by kiwi0fruit** [comment]
Oh. Thanks! I'll try
```py
with enaml.imports():
    from .enaml_video_view import Main
```
and 
```py
with enaml.imports():
    from enaml_video_app.enaml_video_view import Main
```

**Comment by kiwi0fruit** [comment]
This works:
```py
with enaml.imports():
    from .enaml_video_view import Main
```
Thanks again and sorry for bothering with such a stupid mistake.

**Comment by MatthieuDartiailh** [comment]
No problem @kiwi0fruit
