### ISSUE TITLE
enaml-compileall docs

### ISSUE THREAD

**Issue by aarmn** [nucleic/enaml#344]
I searched for compile all command in readthedocs but i cant find anything . can anyone guide me what this command exactly do and what is .enamlc file? How to use it? and ....

**Comment by frmdstryr** [comment]
It's the same as https://docs.python.org/2/library/compileall.html but it also works for enaml files

**Comment by MatthieuDartiailh** [comment]
.enamlc files are the equivalent of .pyc for Enaml. You should never to have to manipulate them directly. The command is there because in large application it may be desirable to compile all enaml file during the install to avoid a long startup time on the first startup.

@frmdstryr since you contributed this command could you add some documentation for it somewhere (not sure what is the best place in the docs).

**Comment by aarmn** [comment]
So how can i run them with enaml-run ? because we can run .pyc files with python command but Im not sure about this. how can I run from .enamlc?
Does it effect on startup speed a lot?

**Comment by aarmn** [comment]
Because I'm using enaml as a lib to make real open-source programs and not just geeky ones. I would be glad if you help me to make changes i need to make it a better app for end-user. and it would be really good to have some option like --release and --debug mode (just an idea :))

**Comment by frmdstryr** [comment]
On normal computers the speed difference is practically negligible. Just use the enaml files.

**Comment by MatthieuDartiailh** [comment]
If you build a real world you will most likely have a python startup file (cf employee tutorial) and not just use `enaml-run`, because you may want to parse command line argument for example. When you import an enaml for the first time a cache file will be created and used for subsequent runs. `compileall` can simply be used to avoid having a difference between the first run and the next ones so no need to worry too much here.

**Comment by aarmn** [comment]
Thanks for All helps.

**Comment by MatthieuDartiailh** [comment]
Closed by #345
