### ISSUE TITLE
Does `alias` need to be a reserved keyword?

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#380]
Not a big deal but could `alias` be changed to not be a keyword and the `alias_expr` merged into `storage_expr` + validation? 

```python
from enaml.widgets.api import Window, Container, Label, PushButton

def build_query():
    import sqlalchemy as sa
    return str(sa.select().alias('blablablba'))

enamldef Main(Window): window:
    Label:
        text = build_query()
```

```python-traceback
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/enaml3/bin/enaml-run", line 11, in <module>
    load_entry_point('enaml', 'console_scripts', 'enaml-run')()
  File "/home/user//enaml/enaml/runner.py", line 45, in main
    ast = parse(enaml_code, filename=enaml_file)
  File "/home/user//enaml/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/home/user//enaml/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "tests/example.enaml", line 7
    return str(sa.select().alias('blablablba'))
    ^
SyntaxError: invalid syntax
```

As a workaround I have to use getattr or push to a separate module... I can submit a PR to review if there are no objections.

**Comment by sccolbert** [comment]
It should only be treated as keyword inside an `enamldef` block. If it’s not allowed outside such a block, that’s a bug we need to fix.

**Comment by MatthieuDartiailh** [comment]
Currently none of the following enaml keywords behave this way: pragma, const, alias, enamldef, template. However attr and func does behave as described by being treated as NAME token. We could change that  for the others too. I fear it may make the grammar ambiguous though. Otherwise we could keep track of the scope in the lexer and turn special tokens to NAME if outside of the proper scope.
No matter the solution we should homogenize the behavior, I think.

**Comment by MatthieuDartiailh** [comment]
Since alias and const follow similar rules to attr we can probably just add branches in the parser functions handling those rules. In that case there is no risk of ambiguity in the grammar. Not sure when I will have time to address this. I would like to finish the copy migration first. If anyone wants to tackle they are welcome.

**Comment by MatthieuDartiailh** [comment]
In order to avoid repeating #381, I would like we agree on the principle of the solution to use. The way I see it we have two solutions:
- implement a new filter on the tokens to convert any token specific to enamldef/template block to a normal name if found outside of such a block (**Note**: I believe those should not be keyword inside declarative functions and operators right hand side). The logic to handle this cannot be done using multiple state lexers since we need the indentation, which is only generated later, to keep track of the state . Furthermore this is likely to be complex since the rules for examples for the :: operator are complex (indentation is only optional)
- our second option is to use bare NAME for `attr, alias, const, func` and then define parsing rules that use the first name of the line to determine the proper AST to generate (it is already the case for attr and func). Those rules have to have some generality since `attr a: int` and `alias a: b` are ambiguous otherwise. 

I am personally in favor of the second solution (the first one seems over complicated and very error prone). I believe that it was the direction taken by #381 even though it was too limited in scope since it was not dealing with `const`. Obviously it means that some existing rules will have to be merged (or turned into simple helper functions). As usual we will have to write the appropriate tests to avoid any regressions.

**Comment by frmdstryr** [comment]
I think the proper way to do this is to enter an inclusive state when entering an enamldef / template block which then adds `alias` and `const` as state specific tokens (see [Conditional lexing and start conditions](http://www.dabeaz.com/ply/ply.html#ply_nn21)).  

I messed with it a little but was still getting the error with ALIAS not being a token and gave up.

**Comment by MatthieuDartiailh** [comment]
This is basically 1 but to detect the end on the block you need the indentation which is generated only later, so it is a new filter not just using the builtin lexer state selection. Also if you want this to work (and I think it is nice):
```python

import sqlalchemy as sa

enamldef Main(Window): window:
    attr q
    Button:
        clicked:: window.q = str(sa.select().alias('blablablba'))
```
The logic to exit the state is fairly involved.

#382 implements solution 2 and seems reasonable to me.

**Comment by frmdstryr** [comment]
Thanks!
